# Generated by Django 4.1.7 on 2023-02-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainModel',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(db_column='Phone Number', max_length=11, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('relation', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='media/user')),
            ],
        ),
    ]
