# Generated by Django 4.1.7 on 2023-02-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainmodel',
            table='User Details',
        ),
    ]
