# Generated by Django 4.1.7 on 2023-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_mainmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='image',
            field=models.ImageField(upload_to='media/user/'),
        ),
    ]
