# Generated by Django 4.1.7 on 2023-03-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_mainmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='status',
            field=models.CharField(default='pending', max_length=20, null=True),
        ),
    ]
