# Generated by Django 4.1.7 on 2026-06-05 08:19

import chatapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=chatapp.models.support_attachment_path),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
