# Generated by Django 4.1.7 on 2023-03-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_set', models.FileField(upload_to='dataset')),
            ],
            options={
                'db_table': 'dataset_file_info',
            },
        ),
    ]
