# Generated by Django 4.1.7 on 2023-03-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_dataset_accuracy_remove_dataset_f1_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithms',
            fields=[
                ('algo_id', models.AutoField(primary_key=True, serialize=False)),
                ('algo_name', models.CharField(max_length=100, null=True)),
                ('accuracy', models.CharField(max_length=500, null=True)),
                ('precision', models.CharField(max_length=500, null=True)),
                ('recall', models.CharField(max_length=500, null=True)),
                ('f1_score', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'Algorithms_details',
            },
        ),
    ]
